variation_name: test_config
looking_for: "pi+_hcal" ## pi+_hcal, pi+_hcal, or e-_hcal
sub_label: "SF_with_logE_4input"
num_input: "4"
#particle=looking_for.split('_')[0]
#detector=looking_for.split('_')[1]

# HCAL INSERT ELECTRON
#h5_filename: '/media/miguel/Elements/Data_hcali/Data1/Jan_2023_log_space_Files/log_uniform_e-_2.83deg_jan26_23_train_split.hdf5'

## HCAL ELECTRON
#h5_filename: '/media/miguel/Elements/Data_hcali/Data1/Jan_2023_log_space_Files/log_uniform_e-_17deg_jan26_23_train_split.hdf5'

## HCALI PION
#h5_filename: '/media/miguel/Elements/Data_hcali/Data1/Jan_2023_log_space_Files/log_uniform_pi+_2.83deg_jan26_23_train_split.hdf5'

## HCAL PION
#h5_filename: '/media/miguel/Elements/Data_hcali/Data1/Jan_2023_log_space_Files/log_uniform_pi+_17deg_jan26_23_train_split.hdf5'

#h5_filename: '/media/miguel/Elements/Data_hcali/Data1/log_uniform_pi+_17deg_500k_train_split.hdf5'
do_input_normalization: True

#n_epochs: 100
#batch_size: 1000
#patience: 10
#loss: 'mae' #mse
#n_latent_dim: 128
#dropout_rate: 0.05

#learning_rate: 1e-3
learning_decay_rate: 0.5

shuffle_split: True #Turn FALSE for images!
train_shuffle: True #Turn TRUE for images!

train_split: 0.6
val_split: 0.25
test_split: 0.15

